dist: focal
language: bash
services: docker

env:
  - VERSION=jdk8 VARIANT=hotspot
  - VERSION=jdk8 VARIANT=openj9
  - VERSION=jre8 VARIANT=hotspot
  - VERSION=jre8 VARIANT=openj9
  - VERSION=jdk11 VARIANT=hotspot
  - VERSION=jdk11 VARIANT=openj9
  - VERSION=jre11 VARIANT=hotspot
  - VERSION=jre11 VARIANT=openj9
  - VERSION=jdk15 VARIANT=hotspot
  - VERSION=jdk15 VARIANT=openj9
  - VERSION=jre15 VARIANT=hotspot
  - VERSION=jre15 VARIANT=openj9

before_install:
  - env | sort
  - cd "${VARIANT}/${VERSION}"
  - image="gradle:${VERSION}-${VARIANT}"
  - docker images --format "table {{.Repository}}:{{.Tag}}" | tail --lines=+2 | grep "adoptopenjdk" | xargs --no-run-if-empty docker pull

install:
  - docker build --tag "${image}" .

script:
  - cd ../../test
  - ./run.sh "${image}" "6.7"
